version: '3.7'

services:
  web:
    image: nginx:alpine
    container_name: bidon-nginx
    ports:
      - "80:80"
    volumes:
      - ./bitrix:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - php-fpm
      - db
    networks:
      - bidon-net

  php-fpm:
    build: ./php
    container_name: bidon-php
    volumes:
      - ./bitrix:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bidon-net
    environment:
      TZ: Europe/Moscow

  db:
    image: mysql:5.7
    container_name: bidon-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: root_password
    networks:
      - bidon-net

  memcache:
    image: memcached
    container_name: bidon_memcache
    restart: always
    ports:
      - "11211:11211"
    networks:
      - bidon-net

  adminer:
    image: adminer
    container_name: bidon-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - bidon-net

  cron-service:
    image: xordiv/docker-alpine-cron
    container_name: bidon-cron
    restart: always
    networks:
      - bidon-net

  ngrok:
    image: ngrok/ngrok
    container_name: bidon-ngrok
    depends_on:
      - web
    command: http web:80
    environment:
      NGROK_AUTHTOKEN: "put ur token here" # Replace with your actual ngrok auth token
    networks:
      - bidon-net

  codeserver:
    image: codercom/code-server:latest
    container_name: bidon-codeserver
    ports:
      - "8082:8080"
    volumes:
      - ./bitrix:/home/coder/project
    environment:
      PASSWORD: "root" # Replace with your desired password for Code Server
    networks:
      - bidon-net

volumes:
  db_data:

networks:
  bidon-net:
